apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trailflow.fullname" . }}
  labels:
    {{- include "trailflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trailflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trailflow.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: trailflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "trailflow.fullname" . }}-config
            - secretRef:
                name: {{ include "trailflow.fullname" . }}-secrets
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
