apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trailflow.fullname" . }}-secrets
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.API_KEY | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.TELEGRAM_BOT_TOKEN | quote }}
  ALLOWED_TELEGRAM_USER_IDS: {{ .Values.secrets.ALLOWED_TELEGRAM_USER_IDS | quote }}
